zdharma-continuum/zinit

zinit-install.zsh

So, since Zsh-Packages no longer exists I suggest we host the packages under the zdharma-continuum org.
I created https://github.com/zdharma-continuum/zsh-package-zsh for example.
Here's what I changed in a nutshell:
- the `pack` ice will look for packages in `zdharma-continuum/zsh-package-${PACKAGE_NAME}`
- Also I updated the default branch for these packages to main (this is debatable but since there
Fixes #3

Fix pack ice

---

README.md
doc/CHANGELOG.md

Since they were mentionned in the README. I created the repos for:
- https://github.com/zdharma-continuum/zsh-package-firefox-dev
- https://github.com/zdharma-continuum/zsh-package-any-node
- https://github.com/zdharma-continuum/zsh-package-any-gem
This PR fixes the URLs that link to these

Fix zinit package URLs

---

doc/CHANGELOG.md

Honk, honk.
As mentioned in #12 we really should be announcing our new home address in the changelog.
Let me know if you think this needs to be worded differently.

Announce zdharma-continuum in CHANGELOG

---

share/deploy_doc.sh

Only use `[@]` as only content of a string. e.g., "${foo[@]}"
From z-shell/zinit#5

fix: use [*] inside arbitrary strings.

---

doc/install.sh

The yes/no prompt doesn't need backslash escaped characters.
From z-shell/zinit#3

fix: read without -r is generally bad.

---

zinit-install.zsh

You cannot refer to a variable in the same statement as it is declared.

fix: package are broken again

---

README.md

I don't think its fair to have psprint's real name hilighted so prominently in
the disclaimer.
Sure, we can link to his profile - if he decides to put his real name on there
that's his choice. Anyway, we shouldn't make this decision for him. We
aren't at war with the poor guy.

No more name calling

---

README.md
doc/CHANGELOG.md
doc/install.sh
doc/zinit.1
zinit-install.zsh

See https://github.com/zdharma-continuum/zinit/issues/38
~~DO NOT MERGE YET. The repos have not been renamed yet.~~ DONE!

Update annexes repo names

---

doc/install.sh

- Update default install dir to XDG_DATA_HOME/zinit/zinit.git (https://github.com/zdharma-continuum/zinit/issues/40)
- Shellchecked the install script
- Updated references to zdharma, the wiki etc.
- Bonus: One can now set the branch to use for installs via `ZINIT_BRANCH` (defaults to master) This might be useful for development, CI and when (if!) we decide to update change the main branch of zinit to "main".

Update the installer!

---

zinit-install.zsh

Fixes issue where Neovim uses `macos` as a descriptor and fails to download.

(bugfix): add macos as possible release descriptor

---

zinit-autoload.zsh

https://github.com/zdharma-continuum/zinit-module/commit/a1125ba updated the path of the compiled module, but it's not reflected in the output after a successful build by 'zinit module build'.
Update the .zinit-module function to print the correct module path.

Print the correct module path

---

zinit-autoload.zsh

Follow-up to https://github.com/zdharma-continuum/zinit/pull/82
Above PR removed the custom `.gitattributes`, this get rid of the related 
custom git config.
Refs:
- #36

✂ Remove custom git config for new plugins

---

zinit-autoload.zsh

Right now, the *second* call to `zinit module build`leads to:
```zsh
$ zi module build
fatal: destination path '/home/pschmitt/.local/share/zinit/module' already exists and is not an empty directory.
Failed to clone module repo
```
This PR addresses this by clearing the local repo and pulling from the remote if the module repo is already on disk.

Fix zinit module build when module repo has already been cloned before

---

zinit-autoload.zsh

🚧 Do not merge yet!
This depends on both: 
- https://github.com/zdharma-continuum/zinit-module/pull/1 
- https://github.com/zdharma-continuum/zinit/pull/86
Changes introduced:
- 🚚 Update module path. I'm planning on moving to the root dir inside the zinit-module dir. This will shorten the module path by one level (no more `module/zmodules`, only `module`)

🚚 module: Get rid of the zdmodules/ dir

---

zinit.zsh

It makes more sense to have it there, since this is the function that is responsible for create all the other dirs.

Move ZINIT[MAN_DIR] creation to .zinit-prepare-home

---

doc/CHANGELOG.md
zinit.zsh

We updated the installer to install to `XDG_DATA_HOME/zinit`, but never updated zinit itself to actually look for its home dir in there.
Note that this also updates the default value `ZINIT[HOME_DIR]` if none of these paths exists to `XDG_DATA_HOME/zinit` (instead of `HOME/.zinit`).
Epic victory royale for the XDG gang.
Refs:
- #61

XDG compliance: `ZINIT[HOME_DIR]` no longer defaults to `HOME/.zinit` but to `XDG_DATA_HOME/zinit`

---

README.md
doc/zinit.1

The install instructions are now shorter!
```zsh
sh -c "$(curl -fsSL https://git.io/zinit-install)"
```

Shorten install url

---

scripts/install.sh
zinit-autoload.zsh

Hundred ~~PRs! 🤯~~ issues! :rofl: 
Refs:
- #46
- #36 
**:warning:  After this is merged we need to RENAME the master branch!**
**:boom: This needs to be done via the UI, otherwise the URLs pointing to /master won't be redirected**
https://github.com/zdharma-continuum/zinit/settings/branches

Update default branch from `master` to `main`

---

docker/Dockerfile
docker/init.zsh
docker/utils.zsh
docker/zshenv
docker/zshrc
scripts/docker-run.sh

Here are a few updates to the docker container.
- annexes get installed by default
- zinit completion
- at container build time `@zinit-scheduler burst` now installs to `/data-static`
- at runtime `/data-static` gets copied over to `/data`. This is necessary because `/data` is meant to be backed via a volume (that's what we do in the zunit tests for instance to verify if we downloaded the files correctly)
- most of the custom stuff (keys setup, annexes, the /data-static to /data file-copy etc) can now be disabled with `NOTHING_FANCY=1` at runtime

🐳 Add annexes to container

---

scripts/install.sh

This installs the annexes with `@zinit-scheduler burst` at install time, rather than when the user first starts zsh after the installation.

Fetch the annexes during the install

---

scripts/install.sh

Currently, the zinit installation script (`scripts/install.sh`) generates the path to zshrc with the following code.
https://github.com/zdharma-continuum/zinit/blob/7f456fdbd419ebdaf68a2aa5b53fd6bd3a4edb48/scripts/install.sh#L308
If `$ZDOTDIR` is set and `$ZSHRC` is not, the right hand side will be evaluated as `$ZDOTDIR`. However, it should be `$ZDOTDIR/.zshrc`.
This PR fixes #119

fix install script

---

doc/CHANGELOG.md
doc/zsdoc/zinit-autoload.zsh.adoc
doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
docker/zshrc
tests/ices.zunit
tests/plugins.zunit
zinit-autoload.zsh
zinit-install.zsh
zinit.zsh

Fixes #111
This also logs an explicit warning when a hook fails:
```
Warning: ∞zinit-compile-plugin-hook hook returned with 1
```

Pedantic warning: Return != 0 when a hook fails

---

docs/Zinit-Packages.md

I'm not familiar with github.io. is changing 'documentation' branch right way to fix [Zinit wiki](https://zdharma-continuum.github.io/zinit/wiki/)?
p.s still most packages in repo are not included in wiki page. i guess we need some script to automatically add/update zinit-package page.

Fix broken zinit-packages links in docs

---

zinit-autoload.zsh

zinit clist assumes that all symlinks in the completions directory are absolute symlinks that resolve to a file in a plugin directory. These two commits ensure:
1) That the symlink resolves to a readable file
2) That the code extracting the plugin ID from a relative symlink to a non-plugin path does not get stuck in an infinite loop.

More robust handling of symlinks in the completions folder

---

zinit-install.zsh

Apparently bzipped archives are already supported. The file extension `tbz` is just not recognized.
Implements #165

Add support for `*.tbz` files

---

zinit-autoload.zsh

When updating zinit or plugins, don't page git log outputs #137

Don't page git log for updates

---

doc/zsdoc/zinit-autoload.zsh.adoc
zinit-autoload.zsh

8355489 Added added a retval variable which is a global variable when a non-parallelized `zinit update` was run. This simply localizes it for parallel and non-parallel runs.

*autoload: Make retval a local variable

---

doc/zsdoc/zinit-autoload.zsh.adoc
doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit-side.zsh.adoc
doc/zsdoc/zinit.zsh.adoc

We have a bunch of PRs that contain this large doc update, obscuring the
actual changes that are being made. This is a one-time, large-scale doc
update. Not sure how things got this out of sync, but we should not have
to do this again.

zinit zshelldoc update

---

.github/workflows/documentation.yaml

We can return the exit code from the same command we print the diff
from.

[CI] Only run git diff once

---

doc/zsdoc/zinit-install.zsh.adoc
zinit-install.zsh

Error loudly instead of silently exiting when erroring due to `jq`
absent.
Closes #135 

maint: check for `jq` command in `.zinit-get-package`

---

doc/zsdoc/zinit-install.zsh.adoc

- regenerate docs for `zinit-install`
Missed in the [initial PR](https://github.com/zdharma-continuum/zinit/pull/202) due to a bug and overlooked in [bugfix PR](https://github.com/zdharma-continuum/zinit/pull/203)

fix: update docs for new jq-check

---

.github/labeler.yml
.github/workflows/labeler.yml

feat: add PR labeler to show what parts of Zinit are changed

---

doc/zsdoc/zinit-autoload.zsh.adoc
zinit-autoload.zsh

fixes bug where zinit self-update was hard-coded to use main, even if it was on a different branch.

(bugfix): zinit self-update uses current branch

---

README.md

Update the `README.md` install command to use Bash due to sh lacking support for `${VAR//foo/bar}` brace substation and breaking the Zinit installer.
See #217 
N/A
See #217

docs: update install command to bash to avoid error

---

README.md

Per the [GitHub announcement](https://github.blog/changelog/2022-04-25-git-io-deprecation/):
> We will be removing all existing link redirection from git.io on April 29, 2022.
Closes #229
Avoid out-of-date documentation
N/A
Manually

docs: remove `git.io` URL use from install command

---

Makefile
scripts/zcompile

- add `zwc` target to compile zinit source to `.zwc`
- add zsh path variable
- add 'test' target to easily run zunit tests
- clean target cleans `.zwc` and more explicit for `.adoc`
- remove `zcompile` script
General repository cleanup
Run zunit via:
```zsh
make test
```
Compile *.zsh files
```zsh
make zwc
```
Manually

maint: update Makefile targets

---

.github/workflows/labeler.yaml

Update trigger for PR labeler GH action workflow.
[Relevant documentation](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)
Make all PR checks pass for external contributions
N/A
N/A

fix: trigger for PR labeler GH action workflow

---

zinit-install.zsh

This codepath was triggered when deleting the whole `~/.ziniti/plugins` dir: during recreation in `.zinit-prepare-home`, `.zinit-compinit &> /dev/null` would be called and the sourcing of `zinit.zsh` would error out with
```
+.zinit-compinit:2> [[.zinit-compinit:2: bad math expression: operand expected at `/Users/jan...'
-n '' ]]
```
As the error was redirected to `/dev/null`, this never showed up. Any zinit install call during that session would not run any hooks as they were not yet registered. The next session would then be fine because the plugins dir would exist. 
See https://github.com/zdharma-continuum/zinit/issues/129#issuecomment-1092111737 -> basically deleting the `~/.zinit/plugins` dir should result in complete recreation on the next run, but due to this bug, it had bad side …

fix: Don't error if $OPTS is not yet defined in .zinit-compinit call

---

.github/workflows/documentation.yaml

Only run documentation (e.g., `zshelldocs`) if changes are made to relevant files.
No need to run on every push if no documentation changes are possible.
N/A
N/A

maint: improve scope of docs workflow triggers

---

.zunit.yml
tests/gh-r.zunit
zinit-install.zsh

- macOS gh-r pattern looks for `.dmg`s
- `gh=r` tests for pulumi, atmos, keepassxc, alacrity, and assh
N/A
Add `gh-r` tests that have `.dmg`

maint: add `dmg` to macos pattern & new gh-r tests

---

zinit-install.zsh

zinit update for every plugin not work.
Occuring error is below
```
.zinit/bin/zinit-install.zsh:1217: parse error near `}'
.zinit-update-or-status:331: command not found: ∞zinit-ps-on-update-hook
...
```
I fixed invalid format `if ((...)) && {` to `if ((...)) {`
Bug fix
PR: https://github.com/zdharma-continuum/zinit/pull/234
issue: #257
It seems to work on my local.

fix: zinit update bug (#257)

---

.zunit.yml
tests/gh-r.zunit

- add `hoofli`, `joincap`, `etcd`, `euterpe`, and `certificates` gh-r tests

maint: add hoofli, joincap, etcd, euterpe, and certificates gh-r tests

---

tests/gh-r.zunit

Add `krew` and `ripgrep-prebuilt` gh-r zunit tests
Never enough tests

feat: add krew and ripgrep gh-r zunit tests

---

.github/workflows/documentation.yaml
doc/zsdoc/zinit-install.zsh.adoc

fix a bug that allowed z-shell docs workflow to pass even though it reported it was out of date.
Code changes were not reflected in technical documentation
N/A
Manually

fix: docs workflow should fail if out-of-date

---

tests/gh-r.zunit

Remove `pokeget` gh-r zunit test due to repository being deleted or made private.
Allow z-unit tests to run full test-suite.
N/A
N/A
Signed-off-by: Vladislav Doster <vladislav.doster@Mastercard.com>

maint: remove the "pokeget" gh-r test due to project being deleted or made private

---

zinit-install.zsh

Fix `gh-r` windows patterns that were missing "("
Remove syntax error
N/A
Manually

fix: unmatched "(" in windows gh-r patterns

---

README.md

README link on front page is broke
Before, 404: https://github.com/zdharma-continuum/zinit/wiki/%F0%9F%9A%9A-Migration-to-zdharma-continuum
With PR: https://github.com/zdharma-continuum/zinit/wiki/Migrating-from-zinit-to-zdharma-continuum
Pure doc fix

docs(README): Fix migration link

---

zinit-additional.zsh
zinit-autoload.zsh
zinit-install.zsh
zinit-side.zsh
zinit.zsh

The patch adds `-o xtrace` to all `emulate -L` calls when needed, i.e.: when already active at the entry to the function.
I've saw some GH issue where this problem, i.e.: of vanishing `xtrace` mode in `emulate -L zsh` functions was described.
Also, the patch adds `builtin` before all emulate calls.

Propagate -o xtrace when needed and prepend builtin to emulate

---

scripts/install.sh
zinit-autoload.zsh
zinit-install.zsh

Remove cURL option `--tcp-fastopen`
Closes #298
N/A
N/A

fix: remove curl option "--tcp-fastopen" which is not always available

---

zinit.zsh

As described in #283
Closes #283
```zsh
+zinit-message "Installed plugin {pid}$1{dbg} id-as is:$id_as"
```
```zsh
+zinit-message "Ran compdef replay{dbg} [count of defs: $count]"
```

feat: debug formatting to `.zinit-message`

---

share/single-line.zsh

Format `share/single-line.zsh` to Zinit's zsh code style convention
Consistency
#238

style: format single-line.zsh to zinit convention

---

zinit-install.zsh
zinit.zsh

Make the `extract''` ice execute earlier in the hook order and make it be always followed for its exclamation-mark modes during `gh-r` and `pack''` downloads.
PR moves `extract''` hook action up, before `atclone/atpull` and before `mv/cp` so that `atclone` can contain `./configure` for the *unpacked* archive. Also, for the `mv''` ice to make sense, as the extension is not required for unpacking (because `file` coreutil is used to find a file of archive type), so one can utilize `mv''` ice for something after the unpacking (not before,  like to rename `mv='tmux->tmux.tgz'` or similar, which wouldn't work  anyway because of the reversed order).
Also, the PR makes the default `ziextract` calling in `gh-r` and `pack''` obey the exclamation marks from `extract'!…'` to allow deciding whether …

Move extract'' action up, before atclone/atpull and before mv/cp

---

zinit-install.zsh

Use CPUTYPE (runtime detected CPU) before using MACHTYPE (compile-time CPU) when installing plugins.
On my system I launch `/bin/zsh` (a universal binary) from [Kitty](https://sw.kovidgoyal.net/kitty/) which is x86_64 only.
Because of the universal binary, zsh has MACHTYPE of x86_64.  The CPUTYPE should be used first to try to install packages with.
Fixes #287 
N/A
On my M1 MBP I deleted and reinstalled `mvdan/sh`'s SHFMT tool.
- [x ] Bug fix (non-breaking change which fixes an issue)
I am unable to get zunit to run at the moment.  Hopefully there is CI that will run it.

fix: use runtime detected cpu before compiled cpu (#287)

---

.github/CODEOWNERS

Information on the [CODEOWNERS file](https://github.blog/2017-07-06-introducing-code-owners).

maint: add CODEOWNERS file for code owners feature

---

.github/ISSUE_TEMPLATE/bug-report.yml

- add OS output labels
- user will abide by code of conduct
Make it easier to debug issues
Currently random values does not handling missing values:
```
linux-gnueabihf | | arm-unknown-linux-gnueabihf | | armv7l unknown
```
Is now usable information:
```
OS: darwin22.0 | Vendor: apple | Machine: x86_64 | CPU: arm64 | Processor: N/A | Hardware: N/A
```
or 
```
OS: darwin22.0 | Vendor: apple | Machine: x86_64 | CPU: arm64 | Processor: arm | Hardware: arm64
```
N/A

maint: improve OS info and CoC agree to issue template

---

.github/workflows/tests.yaml
.gitignore
doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
tests/gh-r.zunit
tests/ices.zunit
tests/snippets.zunit
zinit-autoload.zsh
zinit-install.zsh
zinit.zsh

Exclamation marks (per default) get escaped in interactive mode, but not in non-interactive modes. In this case it meant that zinit would not find any hooks which implements the ices when running in non-interactive mode (e.g. in a script). This in turn would NOT result in errors but would just silently not execute any of the ices which of course would be a bad thing(tm).
This actually happened in the zunit tests as they run non-interactively and therefore any ices based on exclamation mark hooks were not ran. I fixed the few places where (after the fix in this PR) the ice were actually ran and errored due to mis-specifications. I also added explicit checks for a few ices. -> before this PR, ices are basically not tested (and the exclamation mark hook based ones not testable at all!) :-( …

fix: allow zinit to be run from non-interactive scripts

---

tests/gh-r.zunit
zinit-install.zsh

- add `os-x` to darwin gh-r pattern
- add zunit test for tstack/lnav
Closes #367

(fix): add `os-x` to darwin gh-r pattern

---

zinit-autoload.zsh
zinit-install.zsh

replace `egrep` with `grep -E`
grep v3.8 show warning when use egrep
> egrep: warning: egrep is obsolescent; using grep -E
ref: https://www.phoronix.com/news/GNU-Grep-3.8-Stop-egrep-fgrep
```zsh
```

use grep instead of the deprecated egrep

---

zinit-install.zsh

I tried to update plugins today (September 13, 2022) and the binary download from the GitHub release failed.
`gh-r: failed to find the correct GitHub release asset to download.`
It seems that the GitHub website has been updated and the method of parsing assets from HTML no longer works.
Check this command and video.
`curl https://github.com/BurntSushi/ripgrep/releases`
https://user-images.githubusercontent.com/8683947/189714315-fa1d28b0-755a-46f8-9239-5f16291df26b.mp4
I changed the process to get the list of released assets from the API.
This is a temporary patch and we may need to consider a few more things. However, I think it is better than not working.
.zshrc
```zsh
ZPLG_HOME="$HOME/.config/zinit"
if ! test -d "$ZPLG_HOME"; then
mkdir -p "$ZPLG_HOME"
chmod g-rwX "$ZPLG_HOME"
git clone …
```

fix: Fix download from gh-r

---

Makefile
share/template-plugin/template-script
share/zsh.ctags
zi-browse-symbol
zinit.zsh

Just run `make tags` (or more specific targets: tags-vim, tags-emacs) to
obtain a dictionary of all functions and variables.
This can be very handy, especially with a  good editor. Features of `Universal Ctags` are very heavily utilized, although old `Exuberant Ctags` is also supported. I've created a Zsh language definition with use of `pcre` regexps, so be sure to compile this feature into `universal ctags`.
**PS. UPDATE:** A recipe to install `universal ctags` :rofl: zinit has the best support and delivery :smile::
```zsh
zinit id-as null configure'#' make'install' \
for universal-ctags/ctags
```
**Update 2**: Also a recipe for `pcre2-8` which can be used with `uni-ctags` – easy dizzy  – only changed the repo ID :smile:: 
```zsh
zinit id-as null configure'#' make'install' \
for …
```

A zsh language definition for Ctags wrapped in `tags` Make target

---

zinit-additional.zsh
zinit.zsh

Zinit can set temporary, local variables in the moment of loading a plugin, with `param'name->value'`. However, they aren't exported. This PR adds the `-x` option to the `local …` invocation to make variables created with `param'name → value'` be exported.
Also, it makes `*.plugin.zsh` files sourced if any for services plugin besides running `*.service.plugin` in background.
The motivation is to allow configuring a new service that I'm writing via a `param'MAKE_SERVER_SRC_DIRS→~/github/mc'`, without a separate line in `.zshrc`.
```zsh
zi service'make' `param'MAKE_SERVER_SRC_DIRS→~/github/mc'` for zservices/make-server
```
**Update**: I've expanded README.md with `param''` description.

Make variables created with param'name → value' be exported. Also

---

zinit.zsh

I've started a new PR for the global aliases because I haven't been using a separate branch in #371.
The user can use them in 3 ways:
$ cd ZIBIN
$ cd $ZIBIN
$ cd ~ZIBIN
$ cd ZPFX
```zsh
```

Add a few global aliases and vars like ZIBIN, ZIPLUGS and others.

---

zinit.zsh

Add a single conditional that checks if `$ZPFX/man/man1/zinit.1` exists and copies it if not.
There is a manual page of zinit – in `doc/zinit.1`. However I suppose that it's very rarely ever open, because its location under `BIN_DIR`. So I thought that it should be copied to `man1` dir under `ZINIT[MAN_DIR]` so that simple `man zinit` works fine.
```zsh
man zinit
```
```
man zinit
```

Copy zinit.1 to man1 directory for `man` to be able to open it

---

zi-browse-symbol
zinit.zsh

The new Alt-Q key is already bound to push-line, however the zle widget has also two other keys, ctrl-q and Alt-q, so no problem, as IMO users who want that widget already use Alt-q, not Alt-Q.
Also, a way of customizing via `zstyle` `':zinit:browse-symbol:key'`  has been added.
Change the argument of `bindkey`.
Problems with ctrl-k users, e.g.: #386

Assign ctags symbols browser to Alt-Q instead of ctrl-k

---

zinit.zsh

For normal hooks, the exclamation mark handling (which adds entries into `ZINIT_EXTS2`) was fixed in https://github.com/zdharma-continuum/zinit/pull/227 and for both `ZINIT_EXTS` and `ZINIT_EXTS2` the escaped exclamation marks were adjusted. But annexes could also register hooks with exclamation marks into `ZINIT_EXTS` and this part was not modified. Therefore annex registering for exclamation mark hooks did not work anymore.
See above + the part where `ZINIT_EXTS` is modified is now also adjusted in a similar manner as in #227 to not expand history chars (=exclamation marks).
See https://github.com/zdharma-continuum/zinit-annex-patch-dl/issues/6
See https://github.com/zdharma-continuum/zinit-annex-patch-dl/issues/6
The following three prints should all three print the same (two) lines …

fix: Do not try to escape exclamation marks

---

zinit.zsh

Keep `zinit.1` up to date by comparing timestamps of `~ZIBIN/doc/zinit.1` and of `$ZPFX/man/man1/zinit.1` and copying if the `~ZIBIN` one is more recent.
I've updated `zinit.1` when changed README.md, and noticed that `$ZPFX/man` isn't updated. I've used `pandoc` from `gh-r`, the latest.
#381 
I've touched `doc/zinit.1` and started a new `zsh`.

Copy zinit.1 if it's more recent from the one at $ZPFX/man.

---

zinit-install.zsh

fix: gh-r removes linux32 assets on 64 bit OS

---

zinit-install.zsh

Fix regex to disregard `file` output regarding support for different systems.

fix: ziextract execs discovery regex

---

zinit-install.zsh

fix: rm linux32 assets in aarch64/arm64 gh-r regex

---

zinit.zsh

Reverts zdharma-continuum/zinit#419
I'm actually not sure this fix was right to merge. Undoing for now.

Revert "Copy doc/zinit.1 only if it exists. Fixes #418."

---

zinit.zsh

Change the time interval for the scheduler to check for queued tasks to ten seconds.
Lower system resource usage.
#362

Make scheduler be called in 5 seconds interval after no more scheduled tasks

---

zinit.zsh

perf: Make scheduler be called in 10 seconds interval if no tasks

---

README.md
doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
tests/ices.zunit
zinit-install.zsh
zinit.zsh

Adds a new ice called `completions` which, if set, always triggers completion detection and installation.
This can be used to overwrite `as'null'` which would otherwise not trigger completion detection and installation. It would also overwrite a `nocompletions` ice, if both are set, e.g. via using the default ice annex.
I use default ice to set `zinit default-ice --quiet as'null' from"gh-r" lbin'!' lucid nocompile` for my list of gh-r downloads. Unfortunately, this disables the import of completions:
To reproduce:
```
zinit default-ice --quiet as'null' from"gh-r" lbin'!' lucid nocompile
zinit lbin'!gj' pick'gj*.tar.gz' atclone'./gj completion zsh > _gj'  atpull'%atclone' for @rsteube/go-jira-cli
zinit clist | grep _gj # -> no _gj completion
```
Set default ice
```
zinit default-ice …
```

feat: add completions ice

---

doc/zsdoc/zinit-autoload.zsh.adoc
zinit-autoload.zsh

fix: use correct return code in zinit-confirm

---

tests/plugins.zunit
zinit-install.zsh

Run `creinstall .` in the `﻿zsh-users/zsh-completions` plugin folder manually, then the symbolic links in the completions folder are broken.
I found this issue when running `zinit update` with the following minimal setup.
```zsh
zinit wait lucid light-mode for
blockf atpull'zinit creinstall -q .' \
zsh-users/zsh-completions
```
```zsh
$ find ~/.local/share/zinit/completions -xtype l | wc -l # no broken symbolic links before creinstall
0
$ pwd
~/.local/share/zinit/plugins/zsh-users---zsh-completions
$ zinit creinstall -q .
Installed 139 completions. They are stored in the $INSTALLED_COMPS array.
$ find ~/.local/share/zinit/completions -xtype l | wc -l # count broken symbolic links
139
$ ls -l ~/.local/share/zinit/completions
total 560
lrwxrwxrwx 1 miles miles 11 Jan  7 11:14 _afew -> …
```

fix: broken symbolic link after `creinstall .`

---

zinit.zsh

The useful %x prompt expansion can be used to get path to the executed script: `0=${(%):-%x}`
It is always the correct, expected value, even for autoloaded functions. However, it currently doesn't work with Zinit special fpath-pollution free autoload. This patch fixes this.
It is comfortable to get correct `$0` even for autoloaded functions with:
```zsh
0=${(%):-%x}
```
However to make it fully work under Zinit, it has to define its emulated autoload function with:
```zsh
functions[func]="…"
```
instead of:
```zsh
eval "function func { …"
```
because the eval method returns wrong path at first function execution (returns path to `name.plugin.zsh` instead). That's the change of this PR.
The change has to work, it's very isolated.

fix: assign to functions hash to make %x work

---

doc/zsdoc/zinit-install.zsh.adoc
zinit-install.zsh

Make `grep` search case-insensitive requirement when using the `gh-r` ice.
Closes #476

fix: make `gh-r` release version search case-insensitive

---

README.md

The error may be caused by the space after the backslash, and `sh` requires that the character after the backslash should be `\n` to be regarded as a continuation line
> A backslash preserves the literal meaning of the following	character, with the exception of the newline character	(`\n'). A backslash preceding a newline is treated as a line continuation.
refer to https://man.freebsd.org/cgi/man.cgi?query=sh
Fixed wrong starship example in `README.md`
This PR addresses the unfixed issues raised by https://github.com/zdharma-continuum/zinit/issues/271, and makes the starship example work fine
https://github.com/zdharma-continuum/zinit/issues/271
Same as the original usage

fix: the starship example does not work properly

---

doc/zsdoc/zinit-autoload.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
zinit-autoload.zsh

- Update set of options that are passed to Pygmentizea 
- Use consistent logging style
- Use long flags to improve grokability
The `glances` subcommand works again.

fix: update `pygmentize` flags in glance subcommand

---

.github/labeler.yml
.github/workflows/tests.yaml
doc/zsdoc/zinit-autoload.zsh.adoc
doc/zsdoc/zinit-side.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
tests/commands.zunit
zinit-autoload.zsh
zinit.zsh

- `zinit delete` command can delete multiple plugins at once
- remove broken symlinks after deleting a plugin
- improve option parsing (i.e., `--all` and `--clean` are mutually exclusive, don't default to deleting snippets)
- track number of failed deletions
Increase usability and reduce duplicate tasks.
Closes #239
```zsh
```

[DNM] feat: delete multiple plugins at once

---

.github/workflows/documentation.yaml
.github/workflows/tests.yaml
_zinit
doc/zsdoc/zinit-autoload.zsh.adoc
doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
tests/commands.zunit
zinit-autoload.zsh
zinit.zsh

- `delete` subcommand can now take multiple arguments
- improved logic for `--all`, `--clean` flags
- improved log output
- now cleans up broken symlinks
```
zinit delete <Plugin> <Plugin> ...
```
Closes https://github.com/zdharma-continuum/zinit/issues/57
Closes https://github.com/zdharma-continuum/zinit/issues/239
Usability
Closes #239
Closes #57
zi delete --help
Left side is proposed changes and right side is current Zinit.

fix: delete multiple plugins at once

---

zinit-autoload.zsh

The `csearch` command now ignores lua files that start with `_`.

fix: `csearch` ignores lua files

---

doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
zinit-install.zsh
zinit.zsh

Update completion and compile log messages.

fix: compile and completion log messages

---

.github/workflows/containers.yaml

This PR builds an OCI image with zsh 5.9
Note: this depends on https://github.com/zdharma-continuum/zinit-packages/pull/13
*N/A*
```zsh
podman run ghcr.io/zdharma-continuum/zinit:zsh-5.9
```

feat: build container with zsh 5.9

---

.github/workflows/containers.yaml

The containers should only be built when pushing to main.

ci: only build containers on main branch

---

tests/gh-r.zunit

Pin gh-r test for [pkolaczk/fclones](https://github.com/pkolaczk/fclones) due to latest release missing assets.

fix: pin `fclones` gh-r test version to v0.30.0

---

.github/workflows/documentation.yaml
tests/gh-r.zunit

This makes the pipeline **commit** the generated docs to the current branch.
Should make it easier for people w/o docker (@psprint) to contribute.
⚠️ To verify that this works I altered `zinit.zsh`, this file needs to be reset before we merge this in!
```zsh
print 'N/A'
```

ci: commit generated docs

---

tests/gh-r.zunit

Fixes rhe gh-r test for hub (formerly github/hub, now mislav/hub).
See the redirect happening here: https://github.com/github/hub
```zsh
zinit from"gh-r" nocompile lbin'!' cp"hub-*/etc/hub.zsh_completion -> _hub" for @mislav/hub
```

ci: fix repo for hub (github -> mislav)

---

zinit-install.zsh

There are unquoted parens (…) in the message, causing it to fail.
Before:
After:

fix: quote parens so that they aren't used as globs

---

doc/zsdoc/zinit-autoload.zsh.adoc
doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit-side.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
zinit-autoload.zsh
zinit-install.zsh
zinit-side.zsh
zinit.zsh

- Rename all instances of `+zinit-message` to `+zi-log`
- Maintain compatibility with community plugins/annexes by forwarding `+zinit-message` calls to `+zi-log`

refactor: rename `+zinit-message` to `+zi-log`

---

README.md

As @alichtman noted the `$ZPFX` variable isn't documented (https://github.com/zdharma-continuum/zinit/pull/547#issuecomment-1685376265). This PR adds information on the var to the readme.
#547 
To make users understand what `$ZPFX` is and what `configure''` and `make''` ices are doing.
With grip npm package.

docs: document $ZPFX variable in README

---

tests/gh-r.zunit

Handles programs that create a config dir on first invocation and cluttered users $HOME dir.
Annoyed

fix: set home dir to test env in gh-r tests

---

README.md
_zinit
doc/CHANGELOG.md
doc/zsdoc/zinit-install.zsh.adoc
zinit-autoload.zsh
zinit-install.zsh
zinit.zsh

The `clist` subcommand has been renamed to `completions` to reduce duplicated commands.
Closes #569

refactor: `clist` subcommand renamed to `completions`

---

zinit-autoload.zsh

`zinit delete` option flags can go before or after positional arguments.

fix: respect delete flags after positional arguments

---

zinit-install.zsh

`arch` command is not available for systems that do not have GNU coreutils installed. it isn't installed on Synology or NixOS for example.
Closes #585

fix: use MACHTYPE instead of arch binary

---

doc/zsdoc/zinit-install.zsh.adoc
tests/gh-r.zunit
zinit-install.zsh

Skip compile if from'gh-r' ice is set unless compile is also set.
**Old behavior left** & **New behavior right**

fix: from'gh-r' skips compile by default

---

doc/zsdoc/zinit-install.zsh.adoc
doc/zsdoc/zinit.zsh.adoc
zinit-install.zsh
zinit.zsh

Using '{dbg}' in +zi-log (i.e., `+zi-log '{dbg} foo bar'`) will only print when "$ZINIT[DEBUG]" is set
```zsh
+zi-log "{dbg} foo bar"
```

fix: debug logging logic and format

---

tests/commands.zunit
zinit.zsh

Fix error when running:
```zsh
zinit --help
```
Closes #593 
```zsh
zinit --help
```
Added zunit tests for `help`, `-h`, `--help`

fix: handle zinit --help

---

.github/workflows/tests.yaml
tests/_support/annex_test_assertions
tests/_support/bootstrap
tests/commands.zunit
tests/gh-r.zunit
tests/ices.zunit
tests/plugins.zunit
zinit-autoload.zsh
zinit-install.zsh
zinit.zsh

- 'configure' and 'make' ices refactored
- new 'build' ice sets 'configure' and 'make ices if no flags are needed.
- new 'cmake' ice will build/install using 'cmake'
- Delete command now handles programs using 'make' and 'cmake' ices
- zunit tests added
- Setting `ZINIT[DEBUG]` enables debug logging (i.e., `+zi-log "{dbg} message ..."`)

feat: configure, make, cmake, and build ices

---

.github/workflows/tests.yaml
.zunit.yml
doc/zsdoc/zinit-install.zsh.adoc
tests/_support/annex_test_assertions
tests/_support/bootstrap
tests/commands.zunit
tests/gh-r.zunit
tests/ices.zunit
tests/plugins.zunit
zinit-autoload.zsh
zinit-install.zsh
zinit.zsh

* Refactored 'configure' and 'make' ices
* New 'build' ice sets 'configure' and 'make ices if no flags are needed.
* New 'cmake' ice will build/install using 'cmake'
* Delete command now handles programs using 'make' and 'cmake' ices
* Zunit tests added
* Setting `$ZINIT[DEBUG]` enables debug logging (i.e., `+zi-log "{dbg} message ..."`)
```zsh
```

feat: configure, make, cmake, and build ices (#613)

---

zinit.zsh

Not sure when this got changed, but reverting to blue to follow Homebrew log colors.

style: change log message prefix color to blue

---

_zinit
zinit-autoload.zsh

Fix issue when deleting a plugin did not unset variables containing plugin state. This manifested in incorrect command output.
Add `--debug` && `--quiet` flags to `delete` command.
- `--debug` flag enables xtrace for the currect delete command invocation
- `--quiet` flag suppresses some output  
---

feat(delete): fix unsetting plugin state & add `--debug` / `--quiet` flags

---

tests/commands.zunit
zinit-autoload.zsh

fix:  `plugins` command correctly handles keyword argument

---

.github/workflows/release.yml

ci(release): bump zinit homebrew formula

---

tests/gh-r.zunit

The latest [`fx` release `33.0.0`](https://github.com/antonmedv/fx/releases/tag/33.0.0) has no assets (as of 1710805662) breaking zunit tests.

test(fx): pin version to 32.0.0

---

zinit-autoload.zsh

If `git` is aliased to something that doesn't work identically (e.g. [bit](https://github.com/chriswalz/bit)) then `zinit update <plugin>` can fail, as well as `zinit version`
Most other instances of `git` already use `command git`, there was just a few missing.

fix: add `command` before instances of `git` that didn't have it

---

zinit-install.zsh

Simplify `.zinit-setup-plugin-dir` protocol pattern
```zsh
test_patterns=(' ' '' 'fgit' 'ftp' 'ftps' 'ftpx' 'ghttps' 'git' 'http' 'https' 'httpss' 'httpx' '  http' 'ssh' 'rsync')
protocol_pattern='(|ftp(|s)|git|http(|s)|rsync|ssh)'
for p in $test_patterns[@]; do
url="${p}://test-url.com";
if [[ ${url} = ${~protocol_pattern}://* ]]; then
P -P "%F{green}pass%f: ${(qqq)p}"
else
P -P "%F{red}fail%f: ${(qqq)p}"
fi
done
```
```console
fail: " "
fail: "fgit"
pass: "ftp"
pass: "ftps"
fail: "ftpx"
fail: "ghttps"
pass: "git"
pass: "http"
pass: "https"
fail: "httpss"
fail: "httpx"
fail: "  http"
pass: "ssh"
pass: "rsync"
```

fix(zinit-install): simplify protocol pattern

---

zinit-install.zsh

- [Improved maintanability / reducing boilerplate code] Refactored code to share the same code basis for ICE `cp` and `mv`
- [New feature] Allows the user to provide multiple files in the `cp` / `mv` ICE separated by `;` This aligns with other ICE options, where the user can provide multiple files.

Allows the user to provide multiple files in the `cp` / `mv` ICE separated by `;`

---

zinit-install.zsh

"pair" variable was not localized within ∞zinit-file-cp-mv-operation function
Fixes `∞zinit-file-cp-mv-operation:16: scalar parameter pair created globally in function ∞zinit-file-cp-mv-operation` message during mv/cp operations using this function
Rerunning the operation that caused the error:

fix: global variable in ∞zinit-file-cp-mv-operation

---

tests/gh-r.zunit

There's no mac-os release: https://github.com/denisidoro/navi/releases/tag/v2.24.0

ci: disable navi gh-r test on mac os

---

.github/workflows/containers.yaml

ci: disable container builds for old versions of zsh
