README.md
- add missing `zsh` language hint for code fences
- consistent `md` formatting
- update links
- remove donation links
=> (maint): update links to point towards `zdharma-continuum`

README.md
make readme.md more useful
see https://github.com/zdharma-continuum/zinit/issues/2
=> fix: update `zdharma` to `zdharma-continuum`

zinit-autoload.zsh
=> Fix asynchronous update message

README.md
=> Add link to migration wiki page

doc/install.sh
=> Use 'mktemp -d' for macos compatibility

.github/workflows/gh-pages.yaml, docs/index.md
This is very first batch of CI that can be merged w/o headaches!
Here the workflow for maintainer/contributors:
- edit the mkdocs in the `documentation` branch
- git push your changes
- Refresh https://zdharma-continuum.github.io/zinit/wiki/
See also: #42
=> 🤖 Auto build and publish via GitHub Actions

docker/Dockerfile, docker/zshenv, scripts/docker-build.sh, scripts/docker-run.sh
Should fix the plugin zunit test :)
=> Make sure TERM is set in the container. Fixes #97

scripts/install.sh
Fix wrong(old) function calls for print warning message in install script.
=> Fix warning messages

.github/workflows/linting.yaml
It's basic AF but it's something.
zsh -n ftw.
=> Basic linting 🤗

zinit-autoload.zsh, zinit.zsh
=> Translate Polish comments to english

.github/workflows/documentation.yaml, Makefile, doc/HACKING.md, scripts/docker-run.sh
So here we go. It's all using the zinit container.
Refs:
- #185
- #196
=> Use container for generating docs

share/git-process-output.zsh
- use a single style for the progress bar style
- simplify logic
See #171 for the initial conversation around this change.
=> feat(git-process-output): simplify progress-bar

.github/workflows/linting.yaml, README.md, doc/CHANGELOG.md, doc/HACKING.md, doc/zsdoc/README.md, scripts/docker-build.sh, scripts/docker-run.sh, scripts/install.sh, scripts/zunit-tests.sh
=> feat: expand linted file types to markdown and shell

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/maintenance.yml
Add issue templates `maintenance` and update templates with labels and titles.
Improve categorization of new issues
N/A
N/A
- [N/A] I have added tests to cover my changes.
=> maint: update issue templates for improved categorization & information

.github/workflows/documentation.yaml, Makefile, doc/zsdoc/zinit-install.zsh.adoc, doc/zsdoc/zinit-side.zsh.adoc, doc/zsdoc/zinit.zsh.adoc, zinit-install.zsh, zinit-side.zsh, zinit.zsh
Fix issue(s) blocking the ability to merge PRs.
The PRs have been open for months and could discourage new contributions.
See #190 && #153 
N/A
By hand, but very thoroughly.
=> doc: improve zsd gen, pdf output, and gh workflow

tests/gh-r.zunit
Add hadolint (dockerfile linter) gh-r zunit test
Increase confidence in gh-r selection logic
N/A
Zunit
=> maint: add hadolint (dockerfile linter) gh-r zunit test

tests/plugins.zunit
=> feat: add compile vim from source zunit test

tests/gh-r.zunit
Add gh-r zunit tests for atuin, compress, gosu, and v
N/A
N/A
N/A
=> maint: gh-r tests for atuin, compress, gosu, and v

tests/gh-r.zunit, zinit-install.zsh
See #228 & #243
Closes #243
New unit tests
=> fix: modify regex in gh-r for assets to not consider for selection

tests/annexes.zunit, tests/gh-r.zunit, tests/plugins.zunit, tests/snippets.zunit
- Condense `snippets.zunit` test verification logic
- Add test for `tldr` completion
- Reduce duplicate logic
N/A
N/A
=> maint: refactor `snippets.zunit` & add multiple tests

.github/workflows/tests.yaml
Use `--tap` flag to reduce zunit test output
Reduce log vomit
N/A
N/A
=> maint: use --tap flag to reduce zunit test output

.github/workflows/delete-old-workflows.yml
add GH action to remove old workflow logs
No need to have 5000+
N/A
Personal repositories
=> feat: add GH action to remove old workflow logs

.github/workflows/documentation.yaml
Only run `zshelldocs` workflow when relevant files have changed.
Faster iteration
N/A
N/A
=> maint: improve gh actions trigger for zshelldocs

.zunit.yml, tests/gh-r.zunit
- Add tests for `moonwalk`, `helix`, `wtf`, `alist`, `moonwalk`, and `warp`
- Add descriptions for multiple programs
- Improve test coverage
N/A
Zunit
=> maint: add warp & moonwalk tests && add misc. descriptions

tests/gh-r.zunit, zinit-install.zsh
=> [DNM] maint: modify linux-(gnu|musl) patterns

.github/workflows/tests.yaml
Take advantage of improvements to Zunit made to our fork
QoL improvements to Zunit
N/A
Locally
=> maint: use `zdharma-continuum` zunit repository

tests/gh-r.zunit
=> maint: add `got` binary to gh-r tests

.github/workflows/tests.yaml
Expand OS versions that are tested against
Lower possibility of breaking a users Zinit configuration.
N/A
Github Actions
=> [DNM] maint: expand systems (macos-{12,10.15} & ubuntu-{22.04,18.04} for unit tests

CODE_OF_CONDUCT.md
Format CODE_OF_CONDUCT.md to our markdown style
N/A
N/A
GitHub actions workflow
=> style: format CODE_OF_CONDUCT to fix failing test

zinit.zsh
Described in #285
To be able to do this:
=> feat: automatic log formatting function

doc/zsdoc/zinit.zsh.adoc
Generate documentation for #290
Fix failing test
N/A
N/A
=> docs: updates for "zinit-formatter-auto" code

doc/zsdoc/zinit.zsh.adoc
Generate documentation for #286
Fix failing tests
N/A
N/A
=> docs: updates for "zinit-formatter-dbg" code

tests/gh-r.zunit
`alist` project ownership was transferred from user`Xhofe` to organization `alist-org`
Fix failing tests in PR #304 
N/A
N/A
=> fix: alist repository for gh-r test

doc/zsdoc/zinit-autoload.zsh.adoc, zinit-autoload.zsh
- logging style consistency 
- update git command for getting current branch to work with older versions (#303)
Closes #303
N/A
Manually :(
=> refactor: self-update logic & logging

.github/workflows/documentation.yaml
- correct typo (e.g., `branchs` -> `branches`)
- add `main` branch to pull request trigger
Stop duplicating documentation job
N/A
N/A
=> fix: typo & triggers in documentation workflow

zinit.zsh
The update does  the following:
1. It makes `a/b` strings be recognized as plugin ids (plus the previous way of recognition via a test to the disk, for single-word id-as plugins).
2. It makes ices with values that contain spaces correctly handled.
3. It makes Oh My Zsh shrothands like `OMZP:`,`OMZL`, etc. recognized as plugin ids.
4. It colorizes numbers with {num}  and time notions (like, e.g.: `3s`) with a new code {time} (color 220 – gold).
The {auto} formatter does an useful job of colorizing text messages, however the lack of space support and of regular plugin ids and nums/times was a serious drawback.
```zsh
+ziinit-message '{auto}Plugin a/b installed in 10s'
```
Despite that I'm now on a bigger machine than Eee PC (core i5), I cannot run the doc/container target because there …
=> Update of the {auto} formatter / again no docs :/

doc/zsdoc/zinit.zsh.adoc
Documentation for changes in PR #311
N/A
=> docs: update info for .zinit-formatter-auto

share/git-process-output.zsh
Format `share/git-process-output.zsh` to project wide convention
See #238
Manually & Z-unit tests
=> style: re-format `git-process-output.zsh` to zinit convention

share/rpm2cpio.zsh
- Format `share/rpm2cpio.zsh` to project-wide convention
- Update copyright notice
See #238
Manually & Z-unit tests
=> style: re-format rpm2cpio.zsh to zinit convention

LICENSE
update copyright declarations
#238
N/A
N/A
=> maint: update license

doc/zsdoc/zinit-install.zsh.adoc
=> docs: update zinit-install.zsh.adoc

doc/zsdoc/zinit-side.zsh.adoc, zinit-side.zsh
Format `zinit-side.zsh` to zinit style convention
#238
#238
Zunit & manually
=> style: format zinit-side.zsh to zinit convention

.gitattributes
Set the EOL and TEXT markers in the gitattributes file.
I noticed some of the changelog had CRs when I did an update and thought if people are using Windows, we should setup .gitattributes to work correctly for them.
```zsh
```
=> git: control EOLs and text marking

.github/CODEOWNERS
=> Hfeat: add CODEOWNERS (core team + psprint)

README.md
- Fixes failing markdown linting test
=> docs: format README.md

README.md
- Fixes failing markdown linting test
```zsh
```
=> docs: format README.md (#347)

doc/zsdoc/zinit-install.zsh.adoc, doc/zsdoc/zinit-side.zsh.adoc, doc/zsdoc/zinit.zsh.adoc
=> docs: configure"" ice updates

tests/gh-r.zunit
=> fix: calico gh-r zunit test

tests/_support/annex_test_assertions, tests/annexes.zunit
- refactor duplicate logic
- add test for `zinit-annex-pull` annex
=> maint: refactor duplicate test logic into function

.github/workflows/tests.yaml
=> fix: remove macOS 11 from test matrix

zinit.zsh
Reverts zdharma-continuum/zinit#378
=> Revert "Add a few global aliases and vars like ZIBIN, ZIPLUGS and others."

docker/init.zsh, docker/utils.zsh, docker/zshenv, docker/zshrc, docker/zshrc-fancy, scripts/docker-build.sh, scripts/docker-run.sh, scripts/install.sh, share/git-process-output.zsh, share/rpm2cpio.zsh, share/single-line.zsh, share/template-plugin/template-script, zi-browse-symbol, zinit-additional.zsh, zinit-autoload.zsh, zinit-install.zsh, zinit-side.zsh, zinit.zsh
=> maint: consistent vim mode lines across all files

_zinit
=> maint: re-format `_zinit`

Makefile
tags still point to tags-emacs etc. while it should be tags/emacs, etc.
=> Fix tags deps.

.github/workflows/tests.yaml
=> fix: zunit install in GH workflow

doc/zsdoc/zinit-install.zsh.adoc, zinit-install.zsh
=> style: update ziextract log messages prefix

zinit.zsh
Some distributions don't provide zinit.1 man page, so first check if it's available.
To fix #418.
#418 
```zsh
```
=> Copy doc/zinit.1 only if it exists. Fixes #418.

.commitlintrc, .github/workflows/linting.yaml
=> ci: add commit linting via commitlint

tests/gh-r.zunit, tests/plugins.zunit
=> fix: remove broken gh-r zunit test for "warp"

zinit.zsh
Reverts zdharma-continuum/zinit#429
=> revert: "perf: Make scheduler be called in 10 seconds interval if no tasks"

.github/workflows/tests.yaml, .gitignore, .zunit.yml, doc/zsdoc/zinit-install.zsh.adoc, doc/zsdoc/zinit.zsh.adoc, tests/_support/annex_test_assertions, tests/_support/bootstrap, tests/annexes.zunit, tests/gh-r.zunit, tests/ices.zunit, zinit-install.zsh
=> fix: `gh-r` system arch detection edge-cases

doc/zsdoc/zinit-install.zsh.adoc, zinit-autoload.zsh, zinit-install.zsh
=> fix: gh-r bpick logging

tests/gh-r.zunit
=> ci: add dstask gh-r test

.github/workflows/tests.yaml, doc/zsdoc/zinit-install.zsh.adoc, zinit-install.zsh
=> fix: gh-r pattern for x86_64 linux-gnu systems

tests/gh-r.zunit
=> ci: git-absorb zunit gh-r test

doc/zsdoc/zinit-autoload.zsh.adoc, doc/zsdoc/zinit.zsh.adoc, zinit-autoload.zsh, zinit.zsh
=> refactor: zinit confirmation messages

README.md
Improve installation instructions to avoid error on each terminal startup.
Avoid error on each terminal startup
NA
Using it locally on a fresh zinnia install
Documentation
=> chore(docs): add conditional directory and git cloning calls to setup instructions

doc/zsdoc/zinit.zsh.adoc
Update line count in `zinit.zsh.adoc`
Fix failing zshelldoc CI
Run zshelldoc CI manually. See https://github.com/miles170/zinit/actions/runs/4191095088
=> docs: update line count in `zinit.zsh.adoc`

tests/gh-r.zunit
Ownership changed hands from [Peltoche](https://github.com/Peltoche) to [lsd-rs](https://github.com/lsd-rs/lsd).
Fix failing zunit tests.
=> fix: `lsd` repo owner changed to lsd-rs organization

_zinit, doc/zsdoc/_zinit.adoc
- add all subcommand short & long flags
- handle mutually exclusive options. For example, a user shouldn't be able to select the `--all` flag and a plugin in `zi delete` but should be able to select the `--yes` or `--quiet`.
- handle the zinit limitation of only taking one plugin in various commands (i.e., delete, uncompiled).
Examples:
- Don't show users plugins in the `zi delete` when they have already selected one to avoid an error.
- Only let the user select one flag option in `zinit time`.
Improve ease of use.
=> feat: zinit completion improvements

doc/zsdoc/zinit-additional.zsh.adoc, doc/zsdoc/zinit-autoload.zsh.adoc, doc/zsdoc/zinit-install.zsh.adoc, doc/zsdoc/zinit-side.zsh.adoc, doc/zsdoc/zinit.zsh.adoc
Regenerate documentation via [zshelldoc](https://github.com/zdharma-continuum/zshelldoc).
=> fix: regenerate zinit docs

tests/gh-r.zunit
Add a zunit gh-r test against [fq](https://github.com/wader/fq).
=> ci: fq cli gh-r zunit test

.github/workflows/tests.yaml, tests/_support/gen-ghr-test, tests/gh-r.zunit
=> feat: expand gh-r zunit tests

doc/zsdoc/zinit.zsh.adoc, zinit.zsh
`zinit update` works again
Closes #507 
Closes #502
=> fix: broken update command

_zinit, doc/zsdoc/zinit-additional.zsh.adoc, doc/zsdoc/zinit-autoload.zsh.adoc, doc/zsdoc/zinit.zsh.adoc, tests/gh-r.zunit, zinit-additional.zsh, zinit-autoload.zsh, zinit.zsh
Make debug commands easier to use by grouping them under a `debug` command
- Make it clear that debug commands are related other than they start with `d`
- Clean up the number of base commands
=> feat: refactor debug commands

tests/gh-r.zunit
Changed from `Ellie` to `atuinsh`
=> fix: update gh-r tests

doc/zsdoc/zinit-autoload.zsh.adoc, doc/zsdoc/zinit.zsh.adoc, tests/commands.zunit, zinit-autoload.zsh
=> 545 bug bad math expression in zinit plugins on ubuntu 2204wsl2

tests/gh-r.zunit
- username changed from `b4b4r07` to `babarot`
=> fix: update gomi repo owner

tests/_support/bootstrap, tests/gh-r.zunit
=> ci: speedup zunit bootstrap & add gh-r tests

scripts/docker-run.sh
`zshelldoc` Makefile now expects `prefix`
=> fix: container zshelldoc install

.github/labeler.yml
=> fix: update labeler config to v5

tests/gh-r.zunit
=> fix: pin dua gh-r test to v2.20.3

zinit-install.zsh
=> fix: link ice check in .zinit-download-snippet function

doc/zsdoc/zinit-install.zsh.adoc, zinit-install.zsh
Remove duplicated function to remove confusion
https://github.com/zdharma-continuum/zinit-packages/pull/15
```zsh
```
=> feat: remove zpextract and use ziextract

tests/gh-r.zunit
Latest release removed Linux artifacts breaking #614 build
=> ci: pin mcfly version gh-r test

zinit.zsh
=> fix(configure ice): remove default --quiet flag

tests/gh-r.zunit
`alist-org` renamed to `alistgo`
```zsh
zunit run tests/gh-r.zunit@alist
```
=> fix(gh-r.zunit): `alist` org name

.github/workflows/tests.yaml, tests/gh-r.zunit, tests/snippets.zunit
=> fix: gh-r zunit tests

_zinit
=> fix completions in zinit update

scripts/install.sh
ref: https://github.com/zdharma-continuum/zinit/issues/687
=> installer: Set min zsh version to 5.8
